language: php

php:
  - '7.1'

services:
  - mysql

before_script:
  - composer install
  - echo -e "DB_HOST=localhost\nDB_USER=root\nTEST_DB_NAME=phpclub_test" > .env
  - mysql -e 'CREATE DATABASE phpclub_test;'
  - composer migrate-test

script:
  - vendor/bin/phpunit --testdox

# Cache Composer dist downloads
directories:
  - $HOME/.cache/composer/files

notifications:
  email: false
